- name: Check if Filebeat Kibana Module is enabled
  stat:
    path: /etc/filebeat/modules.d/kibana.yml
  register: stat_result

- name: Enable Kibana Module for Filebeat
  tags: filebeat-install
  shell: filebeat modules enable logstash
  when: stat_result.stat.exists == False

- name: Create Kibana Filebeat Config File
  tags: filebeat-install
  template: src=filebeat_kibana.yml dest=/etc/filebeat/modules.d/kibana.yml
  notify:
    - restart filebeat
