- name: Install NGINX
  yum: name=nginx state=installed

- stat: path=/opt/kibana-4.3.1-linux-x64
  register: st

- name: Extract Kibana
  unarchive: src=kibana-4.3.1-linux-x64.tar.gz dest=/opt
  when: st.stat.exists == False

- stat: path=/opt/kibana4
  register: st
  
- name: Create Symlink
  file: src=/opt/kibana-4.3.1-linux-x64 dest=/opt/kibana4 state=link
  when: st.stat.exists == False

- name: Create systemd File for Logstash
  template: src=systemd.kibana4 dest=/etc/systemd/system/kibana4@.service owner=root group=root mode=0644
  notify:
    - reload systemd
  tags: 
    - config

- name: Set SELinux Stuff
  seport: ports={{ item.kibana_port }},{{ item.nginx_port }} proto=tcp setype=http_port_t state=present
  with_items: '{{kibana_instances}}'

- name: Create Kibana Configs
  template: src=kibana.conf dest=/opt/kibana4/config/kibana.{{ item.instance_name }}.yml
  tags:
   - config  
  with_items: '{{kibana_instances}}'
  notify:
   - restart kibana



- name: Create NGinx-Kibana Configs
  template: src=nginx.conf dest=/etc/nginx/conf.d/kibana.{{ item.instance_name }}.conf
  with_items: '{{kibana_instances}}'
  tags:
   - config
  notify:
   - restart nginx

#- name: Create NGinx-ES-Proxy Configs
#  template: src=nginx-es.conf dest=/etc/nginx/conf.d/es-proxy.conf
#  notify:
#   - restart nginx

- name: Start Kibana Services
  service: name=kibana4@{{ item.instance_name }} enabled=yes state=started
  with_items: '{{kibana_instances}}'


- name: Start NGINX Services
  service: name=nginx enabled=yes state=started  

