- name: copy Kibana YUM Repo File
  copy: src=kibana.repo dest=/etc/yum.repos.d/kibana.repo
  tags: kibana-install

- name: Install Kibana
  yum: name=kibana state=latest
  tags: kibana-install

- name: Create Kibana Configs
  template:
    src: "kibana.conf"
    dest: "/etc/kibana/kibana.yml"
    backup: yes
  tags:
   - kibana-config
  notify:
   - restart kibana

- name: Start Kibana Services
  service: name=kibana enabled=yes state=started
